### PR TITLE
add fisher data set for KNN

### PR DESCRIPTION
**Pull request by MikeLing**
This pr is for https://github.com/shogun-toolbox/shogun/issues/3513 and support low-dimension data comparison

### CODE REVIEW

**Comment by karlnapf** [comment]
Where is this dataset from? What does it contain? etc needs some description

**Comment by MikeLing** [comment]
The data set is about  [Ronald Fisher](https://en.wikipedia.org/wiki/Ronald_Fisher)'s measurements of type. The original data set can been download from http://www.math.uah.edu/stat/data/Fisher.html.
The first column(column 0) is about the types of flowers which type 0 is Setosa; type 1 is Verginica; and type 2 is Versicolor. And there are four features from column 1 ~ 4 which are petal width (PW), petal length (PL), sepal width (SW), and sepal length (SL) for a sample of 150 irises. The lengths are measured in millimeters.

**Comment by karlnapf** [comment]
Thanks for the info, this has to be in the file (or another file), so that people who open it can see it straight away

**Comment by karlnapf** [comment]
?

**Pull request closed without merging**
