### PR TITLE
Integration testing data for krr nystrom

### PR DESCRIPTION
**Pull request by cfjhallgren**

### CODE REVIEW

**Comment by karlnapf** [comment]
Closed again?

**Comment by cfjhallgren** [comment]
I saw Abhinav had added testing data for nystrom too so closed it.

**Comment by cfjhallgren** [comment]
Thinking to start working on ALS sampling for nystrom method

**Comment by karlnapf** [comment]
Sure! Want to meet one of these days to discuss?
Also, benchmarking your code would be cool, no? Or an ipython notebook reproducing some results from the paper

**Comment by cfjhallgren** [comment]
Just returned to London - would be great to come by, e.g. Monday or Tuesday. Benchmarking would be cool :)

**Pull request closed without merging**
