### PR TITLE
add QDA integration test data

### PR DESCRIPTION
**Pull request by OXPHOS**

### CODE REVIEW

**Comment by karlnapf** [comment]
thanks!
but does this include the covariance matrices (did you use True to generate)?

**Comment by OXPHOS** [comment]
Nope this one was earlier..I'll update this once the meta example is done.

**Comment by karlnapf** [comment]
Ok so I wont merge just now

**Comment by OXPHOS** [comment]
@karlnapf updated

**Comment by karlnapf** [comment]
thanks!

**Pull request merged**
