### PR TITLE
Added rff.dat file

### PR DESCRIPTION
**Pull request by jonpsy**
Neccesary data for integration check Random Fourier Features
@gf712  review?

### CODE REVIEW

**Comment by gf712** [comment]
Just push this commit hash to the main PR and then we can see if the integration test passes :)

**Comment by NanuSai** [comment]
Okay, main PR CI passes. Good to merge here? @gf712

**Comment by karlnapf** [comment]
This file just didnt exist before right?

**Comment by jonpsy** [comment]
The modified .dat is due to different default parameters.

**Comment by karlnapf** [comment]
I see that makes sense thanks!

**Comment by jonpsy** [comment]
Merge??

**Comment by karlnapf** [comment]
We merge it just before/after the main PR is merged

**Pull request merged**
