### PR TITLE
Remove wrong chi_square data file

### PR DESCRIPTION
**Pull request by syashakash**

### CODE REVIEW

**Comment by karlnapf** [comment]
why is it wrong? some details pls :)

**Comment by syashakash** [comment]
Sorry I forgot to add the message.
These listings generated were from the wrong example code, the integration tests failed as result. Once removed the correct meta example for chi_square will be added and it would be good to go.

**Comment by karlnapf** [comment]
But why deleting it when you plan to add something afterwards?

**Comment by syashakash** [comment]
If I add the new example wouldn't the build fail as then the test will be simply comparing its output with the reference result in `data` which would be wrong. Isn't this why adding a meta example a three step process.
1. Add meta example without `data` update.
2. Update `data` submodule with listings.
3. Add updated `data/` in the PR for meta example.
I hope I have understood [this](https://github.com/shogun-toolbox/shogun/blob/develop/doc/readme/INTERFACES.md#interfaces) clearly.

**Comment by syashakash** [comment]
"_Naturally, these tests depend on executing the corresponding example first. Therefore, running a test does not run the example again, but it simply compares the output to the reference file._"
Isn't this why we have a three step process for adding new meta example.Running the example tests without the .`dat` file in `data/testsuite/meta`and then adding the `.dat` file in the said directory. Then rerunning the test. 
Maybe it is ME who has missed something :)
Please correct me in this if I am wrong in understanding how meta examples additions work :)
Nevertheless I am updating this PR with the new data file.

**Comment by karlnapf** [comment]
This is all correct, but I still dont understand the purpose of this PR if there will be another one that re-introduces a test file. Just **replace** the file rather than deleting it and then re-adding it.

If I am still confused, let me know ;)

**Comment by syashakash** [comment]
I replaced the file with the correct one. 

As already the wrong file has been added to `master`, I thought this might cause Travis to fail, as then the referenced listings and generated listings would be compared.

**Comment by karlnapf** [comment]
lol yeah sure :)

**Pull request merged**
