### PR TITLE
add the mkl regression files

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf

### CODE REVIEW

**Comment by karlnapf** [comment]
Thanks!

**Comment by yorkerlin** [comment]
@karlnapf 
please revert it.
the file is generated by the build from the `develop` branch.

I need to the file generated by the build from the `logdomain` branch. I will resend the file.

**Comment by yorkerlin** [comment]
the file is replaced at
https://github.com/shogun-toolbox/shogun-data/pull/77

**Comment by besser82** [comment]
Reverted in https://github.com/shogun-toolbox/shogun-data/pull/78

**Comment by besser82** [comment]
Merged #77

**Comment by karlnapf** [comment]
@besser82 ?

**Pull request merged**
