### PR TITLE
add banana dataset

### PR DESCRIPTION
**Pull request by yorkerlin**
@karlnapf 
please add this dataset used in the notebook.

### CODE REVIEW

**Comment by besser82** [comment]
Merging…  Please update data-subdir in https://github.com/shogun-toolbox/shogun/issues/2828.

**Comment by karlnapf** [comment]
can you elaborate where this is coming from?

**Comment by karlnapf** [comment]
Can you please put the origin into the file as a comment or so?

**Comment by besser82** [comment]
@karlnapf: Looks like they are from [mldata-repo](http://mldata.org/repository/data/viewslug/banana-ida/)

**Comment by yorkerlin** [comment]
The data set is downloaded from http://sci2s.ugr.es/keel/dataset.php?cod=182


Btw, the data set is used for visualization since  it only contains two
features.
What is more, the data set is also used in  paper, Scalable Variational
Gaussian Process Classification.

On Wednesday, April 22, 2015, Björn Esser <notifications@github.com> wrote:

> @karlnapf <https://github.com/karlnapf>: Looks like they are from
> mldata-repo <http://mldata.org/repository/data/viewslug/banana-ida/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shogun-toolbox/shogun-data/pull/74#issuecomment-95288353>
> .
>


-- 
best,

wu lin

**Comment by karlnapf** [comment]
Both of this should be mentioned in a comment in the file, or in a readme for the file. These anonymous datasets should not be in the repository really.
Could you do that @yorkerlin ? Thanks!

**Pull request merged**
