### PR TITLE
data update for new lda example

### PR DESCRIPTION
**Pull request by shubham808**

### CODE REVIEW

**Comment by karlnapf** [comment]
Is there a PR that uses this yet?

**Comment by karlnapf** [comment]
Ah sorry. Of course there is.

**Comment by karlnapf** [comment]
I’ll wait with this until the other or is good to go ok?

**Comment by shubham808** [comment]
yes thanks :) i am sorry the other is taking so long.

**Comment by karlnapf** [comment]
No worries. Good things take time

**Pull request merged**
